version: "3.9"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  chatdev-api:
    build: ./chatdev-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  chatdev-frontend:
    build: ./chatdev-frontend
    restart: always
    ports:
      - "3000:3000"

volumes:
  chatdev-api-data:
  chatdev-frontend-data:
